### ISSUE TITLE
sse-client folder ist empty

### ISSUE THREAD

**Issue by vanvuongngo** [dillibk777/node-server-sent-events-example#1]
Hi @dillibk777,
thanks for your great Tutorial. Did not heard about sse before. Can you check your sse-client folder? After a git clone it looks empty.

**Comment by dillibabukadati** [comment]
Oops, my bad. Pushing the changes.

**Comment by dillibabukadati** [comment]
Done please check now. Please give a star if like my efforts.

**Comment by vanvuongngo** [comment]
Yes and thank you for your quick Response.
